#!/bin/bash

BLUE='\033[0;34m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

TARGET_DIR=$1
COMPONENT=$2
COMPONENT_SHORT=${COMPONENT:3}
NEW_COMPONENT=$3
NEW_COMPONENT_SHORT=${NEW_COMPONENT:3}

echo -e "${BLUE}│${NC} creating a new ${YELLOW}$NEW_COMPONENT${NC} component in ${YELLOW}$TARGET_DIR${NC} based on ${YELLOW}$COMPONENT${NC}"

#mkdir -p ./components/$TARGET_DIR
#cp -r ./components/$TARGET_DIR/$COMPONENT/ ./components/$TARGET_DIR/$NEW_COMPONENT

mkdir -p ./components/$TARGET_DIR/$NEW_COMPONENT

cp ./components/$TARGET_DIR/$COMPONENT/$COMPONENT_SHORT.config.yml ./components/$TARGET_DIR/$NEW_COMPONENT/$NEW_COMPONENT_SHORT.config.yml
cp ./components/$TARGET_DIR/$COMPONENT/$COMPONENT_SHORT.js ./components/$TARGET_DIR/$NEW_COMPONENT/$NEW_COMPONENT_SHORT.js
cp ./components/$TARGET_DIR/$COMPONENT/$COMPONENT_SHORT.hbs ./components/$TARGET_DIR/$NEW_COMPONENT/$NEW_COMPONENT_SHORT.hbs
cp ./components/$TARGET_DIR/$COMPONENT/$COMPONENT_SHORT.scss ./components/$TARGET_DIR/$NEW_COMPONENT/$NEW_COMPONENT_SHORT.scss

sed -i -e "s/$COMPONENT_SHORT/$NEW_COMPONENT_SHORT/g" ./components/$TARGET_DIR/$NEW_COMPONENT/$NEW_COMPONENT_SHORT.js
sed -i -e "s/$COMPONENT_SHORT/$NEW_COMPONENT_SHORT/g" ./components/$TARGET_DIR/$NEW_COMPONENT/$NEW_COMPONENT_SHORT.hbs
sed -i -e "s/$COMPONENT_SHORT/$NEW_COMPONENT_SHORT/g" ./components/$TARGET_DIR/$NEW_COMPONENT/$NEW_COMPONENT_SHORT.scss

rm ./components/$TARGET_DIR/$NEW_COMPONENT/*-e
